//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipcompliantTax
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.shipcompliant.com/", ConfigurationName="ShipcompliantTax.TaxServiceSoap")]
    public interface TaxServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.shipcompliant.com/GetSalesTaxRatesByAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequest))]
        System.Threading.Tasks.Task<ShipcompliantTax.GetSalesTaxRatesByAddressResponse> GetSalesTaxRatesByAddressAsync(ShipcompliantTax.GetSalesTaxRatesByAddressRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.shipcompliant.com/CalculateSalesTaxDueForOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequest))]
        System.Threading.Tasks.Task<ShipcompliantTax.CalculateSalesTaxDueForOrderResponse> CalculateSalesTaxDueForOrderAsync(ShipcompliantTax.CalculateSalesTaxDueForOrderRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.shipcompliant.com/GetTaxRate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequest))]
        System.Threading.Tasks.Task<ShipcompliantTax.GetTaxRateResponse> GetTaxRateAsync(ShipcompliantTax.GetTaxRateRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.shipcompliant.com/GetVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequest))]
        System.Threading.Tasks.Task<string> GetVersionAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public partial class GetSalesTaxRatesByAddressRequest : BaseRequest
    {
        
        private TaxRateAddressInput addressField;
        
        private System.Nullable<System.DateTime> effectiveDateField;
        
        private TaxSaleType taxSaleTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TaxRateAddressInput Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> EffectiveDate
        {
            get
            {
                return this.effectiveDateField;
            }
            set
            {
                this.effectiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TaxSaleType TaxSaleType
        {
            get
            {
                return this.taxSaleTypeField;
            }
            set
            {
                this.taxSaleTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public partial class TaxRateAddressInput
    {
        
        private string cityField;
        
        private string stateField;
        
        private string street1Field;
        
        private string street2Field;
        
        private string zip1Field;
        
        private string zip2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Street1
        {
            get
            {
                return this.street1Field;
            }
            set
            {
                this.street1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Street2
        {
            get
            {
                return this.street2Field;
            }
            set
            {
                this.street2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Zip1
        {
            get
            {
                return this.zip1Field;
            }
            set
            {
                this.zip1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Zip2
        {
            get
            {
                return this.zip2Field;
            }
            set
            {
                this.zip2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public partial class ZipTaxRate
    {
        
        private double alcoholLowerBoundField;
        
        private double alcoholUpperBoundField;
        
        private ProductType productTypeField;
        
        private string zipField;
        
        private string zipPlus4LowField;
        
        private string zipPlus4HighField;
        
        private SaleType saleTypeField;
        
        private double taxAmountField;
        
        private TaxType taxTypeField;
        
        private TaxUnit taxUnitField;
        
        private VolumeUnit volumeUnitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double AlcoholLowerBound
        {
            get
            {
                return this.alcoholLowerBoundField;
            }
            set
            {
                this.alcoholLowerBoundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double AlcoholUpperBound
        {
            get
            {
                return this.alcoholUpperBoundField;
            }
            set
            {
                this.alcoholUpperBoundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ProductType ProductType
        {
            get
            {
                return this.productTypeField;
            }
            set
            {
                this.productTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ZipPlus4Low
        {
            get
            {
                return this.zipPlus4LowField;
            }
            set
            {
                this.zipPlus4LowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ZipPlus4High
        {
            get
            {
                return this.zipPlus4HighField;
            }
            set
            {
                this.zipPlus4HighField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public SaleType SaleType
        {
            get
            {
                return this.saleTypeField;
            }
            set
            {
                this.saleTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double TaxAmount
        {
            get
            {
                return this.taxAmountField;
            }
            set
            {
                this.taxAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public TaxType TaxType
        {
            get
            {
                return this.taxTypeField;
            }
            set
            {
                this.taxTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public TaxUnit TaxUnit
        {
            get
            {
                return this.taxUnitField;
            }
            set
            {
                this.taxUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public VolumeUnit VolumeUnit
        {
            get
            {
                return this.volumeUnitField;
            }
            set
            {
                this.volumeUnitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public enum ProductType
    {
        
        /// <remarks/>
        Null,
        
        /// <remarks/>
        Ale,
        
        /// <remarks/>
        AppleCider,
        
        /// <remarks/>
        Beer,
        
        /// <remarks/>
        BottleBeer,
        
        /// <remarks/>
        CanBeer,
        
        /// <remarks/>
        Cider,
        
        /// <remarks/>
        DraughtBeer,
        
        /// <remarks/>
        Food,
        
        /// <remarks/>
        KegBeer,
        
        /// <remarks/>
        MaltLiquor,
        
        /// <remarks/>
        MerchandiseNonTaxable,
        
        /// <remarks/>
        MerchandiseTaxable,
        
        /// <remarks/>
        SparklingWine,
        
        /// <remarks/>
        Spirits,
        
        /// <remarks/>
        Wine,
        
        /// <remarks/>
        WineCooler,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public enum SaleType
    {
        
        /// <remarks/>
        Null,
        
        /// <remarks/>
        Both,
        
        /// <remarks/>
        Offsite,
        
        /// <remarks/>
        Onsite,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public enum TaxType
    {
        
        /// <remarks/>
        Null,
        
        /// <remarks/>
        Excise,
        
        /// <remarks/>
        Import,
        
        /// <remarks/>
        Markup,
        
        /// <remarks/>
        Sales,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public enum TaxUnit
    {
        
        /// <remarks/>
        Null,
        
        /// <remarks/>
        Dollar,
        
        /// <remarks/>
        Percent,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public enum VolumeUnit
    {
        
        /// <remarks/>
        Null,
        
        /// <remarks/>
        Bottle,
        
        /// <remarks/>
        Case,
        
        /// <remarks/>
        Gallon,
        
        /// <remarks/>
        Liter,
        
        /// <remarks/>
        Milliliter,
        
        /// <remarks/>
        Ounce,
        
        /// <remarks/>
        Quart,
        
        /// <remarks/>
        Barrel,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public partial class TaxRate
    {
        
        private double alcoholLowerBoundField;
        
        private double alcoholUpperBoundField;
        
        private ProductType productTypeField;
        
        private string regionNameField;
        
        private RegionType regionTypeField;
        
        private SaleType saleTypeField;
        
        private double taxAmountField;
        
        private TaxType taxTypeField;
        
        private TaxUnit taxUnitField;
        
        private VolumeUnit volumeUnitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double AlcoholLowerBound
        {
            get
            {
                return this.alcoholLowerBoundField;
            }
            set
            {
                this.alcoholLowerBoundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double AlcoholUpperBound
        {
            get
            {
                return this.alcoholUpperBoundField;
            }
            set
            {
                this.alcoholUpperBoundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ProductType ProductType
        {
            get
            {
                return this.productTypeField;
            }
            set
            {
                this.productTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RegionName
        {
            get
            {
                return this.regionNameField;
            }
            set
            {
                this.regionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public RegionType RegionType
        {
            get
            {
                return this.regionTypeField;
            }
            set
            {
                this.regionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public SaleType SaleType
        {
            get
            {
                return this.saleTypeField;
            }
            set
            {
                this.saleTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double TaxAmount
        {
            get
            {
                return this.taxAmountField;
            }
            set
            {
                this.taxAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public TaxType TaxType
        {
            get
            {
                return this.taxTypeField;
            }
            set
            {
                this.taxTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public TaxUnit TaxUnit
        {
            get
            {
                return this.taxUnitField;
            }
            set
            {
                this.taxUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public VolumeUnit VolumeUnit
        {
            get
            {
                return this.volumeUnitField;
            }
            set
            {
                this.volumeUnitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public enum RegionType
    {
        
        /// <remarks/>
        City,
        
        /// <remarks/>
        Country,
        
        /// <remarks/>
        County,
        
        /// <remarks/>
        Region,
        
        /// <remarks/>
        State,
        
        /// <remarks/>
        Zip,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public partial class GetTaxRateResponse
    {
        
        private AddressSuggestion addressField;
        
        private Error[] errorsField;
        
        private ResponseStatus responseStatusField;
        
        private TaxRate[] taxRatesField;
        
        private ZipTaxRate[] zipTaxRatesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AddressSuggestion Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Error[] Errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ResponseStatus ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public TaxRate[] TaxRates
        {
            get
            {
                return this.taxRatesField;
            }
            set
            {
                this.taxRatesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public ZipTaxRate[] ZipTaxRates
        {
            get
            {
                return this.zipTaxRatesField;
            }
            set
            {
                this.zipTaxRatesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public partial class AddressSuggestion
    {
        
        private string cityField;
        
        private string countyField;
        
        private AddressDetails detailsField;
        
        private AddressParts partsField;
        
        private string stateField;
        
        private string street1Field;
        
        private string street2Field;
        
        private string zip1Field;
        
        private string zip2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string County
        {
            get
            {
                return this.countyField;
            }
            set
            {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public AddressDetails Details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public AddressParts Parts
        {
            get
            {
                return this.partsField;
            }
            set
            {
                this.partsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Street1
        {
            get
            {
                return this.street1Field;
            }
            set
            {
                this.street1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Street2
        {
            get
            {
                return this.street2Field;
            }
            set
            {
                this.street2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Zip1
        {
            get
            {
                return this.zip1Field;
            }
            set
            {
                this.zip1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Zip2
        {
            get
            {
                return this.zip2Field;
            }
            set
            {
                this.zip2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public partial class AddressDetails
    {
        
        private string cityAbbreviationField;
        
        private string congressionalDistrictField;
        
        private string countyFipsField;
        
        private string timeZoneField;
        
        private string timeZoneCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CityAbbreviation
        {
            get
            {
                return this.cityAbbreviationField;
            }
            set
            {
                this.cityAbbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CongressionalDistrict
        {
            get
            {
                return this.congressionalDistrictField;
            }
            set
            {
                this.congressionalDistrictField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CountyFips
        {
            get
            {
                return this.countyFipsField;
            }
            set
            {
                this.countyFipsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TimeZone
        {
            get
            {
                return this.timeZoneField;
            }
            set
            {
                this.timeZoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TimeZoneCode
        {
            get
            {
                return this.timeZoneCodeField;
            }
            set
            {
                this.timeZoneCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public partial class AddressParts
    {
        
        private string companyField;
        
        private string mailBoxNameField;
        
        private string mailBoxNumberField;
        
        private string postDirectionField;
        
        private string preDirectionField;
        
        private string streetNameField;
        
        private string streetNumberField;
        
        private string streetSuffixField;
        
        private string suiteNameField;
        
        private string suiteNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MailBoxName
        {
            get
            {
                return this.mailBoxNameField;
            }
            set
            {
                this.mailBoxNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MailBoxNumber
        {
            get
            {
                return this.mailBoxNumberField;
            }
            set
            {
                this.mailBoxNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PostDirection
        {
            get
            {
                return this.postDirectionField;
            }
            set
            {
                this.postDirectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PreDirection
        {
            get
            {
                return this.preDirectionField;
            }
            set
            {
                this.preDirectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string StreetName
        {
            get
            {
                return this.streetNameField;
            }
            set
            {
                this.streetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string StreetNumber
        {
            get
            {
                return this.streetNumberField;
            }
            set
            {
                this.streetNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string StreetSuffix
        {
            get
            {
                return this.streetSuffixField;
            }
            set
            {
                this.streetSuffixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SuiteName
        {
            get
            {
                return this.suiteNameField;
            }
            set
            {
                this.suiteNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SuiteNumber
        {
            get
            {
                return this.suiteNumberField;
            }
            set
            {
                this.suiteNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public partial class Error
    {
        
        private string codeField;
        
        private ErrorData dataField;
        
        private string keyField;
        
        private string messageField;
        
        private ErrorTarget targetField;
        
        private ErrorType typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ErrorData Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ErrorTarget Target
        {
            get
            {
                return this.targetField;
            }
            set
            {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public ErrorType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public partial class ErrorData
    {
        
        private AddressSuggestion addressSuggestionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AddressSuggestion AddressSuggestion
        {
            get
            {
                return this.addressSuggestionField;
            }
            set
            {
                this.addressSuggestionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public enum ErrorTarget
    {
        
        /// <remarks/>
        Null,
        
        /// <remarks/>
        Address,
        
        /// <remarks/>
        Age,
        
        /// <remarks/>
        Batch,
        
        /// <remarks/>
        Brand,
        
        /// <remarks/>
        Distributor,
        
        /// <remarks/>
        Product,
        
        /// <remarks/>
        SalesOrder,
        
        /// <remarks/>
        Shipment,
        
        /// <remarks/>
        Tax,
        
        /// <remarks/>
        SSO,
        
        /// <remarks/>
        License,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public enum ErrorType
    {
        
        /// <remarks/>
        Authentication,
        
        /// <remarks/>
        Server,
        
        /// <remarks/>
        Validation,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public enum ResponseStatus
    {
        
        /// <remarks/>
        Failure,
        
        /// <remarks/>
        Success,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public partial class ClearingLicensee
    {
        
        private string nameField;
        
        private string cityField;
        
        private string stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public partial class CalculateSalesTaxDueForOrderResponse
    {
        
        private Error[] errorsField;
        
        private TaxRateAddressOutput processedAddressField;
        
        private ResponseStatus responseStatusField;
        
        private double salesTaxDueField;
        
        private ClearingLicensee clearingLicenseeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Error[] Errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TaxRateAddressOutput ProcessedAddress
        {
            get
            {
                return this.processedAddressField;
            }
            set
            {
                this.processedAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ResponseStatus ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double SalesTaxDue
        {
            get
            {
                return this.salesTaxDueField;
            }
            set
            {
                this.salesTaxDueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ClearingLicensee ClearingLicensee
        {
            get
            {
                return this.clearingLicenseeField;
            }
            set
            {
                this.clearingLicenseeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public partial class TaxRateAddressOutput
    {
        
        private AddressStatus addressStatusField;
        
        private string cityField;
        
        private string countyField;
        
        private string stateField;
        
        private string street1Field;
        
        private string street2Field;
        
        private string zip1Field;
        
        private string zip2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AddressStatus AddressStatus
        {
            get
            {
                return this.addressStatusField;
            }
            set
            {
                this.addressStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string County
        {
            get
            {
                return this.countyField;
            }
            set
            {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Street1
        {
            get
            {
                return this.street1Field;
            }
            set
            {
                this.street1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Street2
        {
            get
            {
                return this.street2Field;
            }
            set
            {
                this.street2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Zip1
        {
            get
            {
                return this.zip1Field;
            }
            set
            {
                this.zip1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Zip2
        {
            get
            {
                return this.zip2Field;
            }
            set
            {
                this.zip2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public enum AddressStatus
    {
        
        /// <remarks/>
        Null,
        
        /// <remarks/>
        AddressOutOfRange,
        
        /// <remarks/>
        AddressSuggested,
        
        /// <remarks/>
        ComponentMismatch,
        
        /// <remarks/>
        MultipleMatches,
        
        /// <remarks/>
        NonDeliverableAddress,
        
        /// <remarks/>
        NoStreetData,
        
        /// <remarks/>
        UnknownStreet,
        
        /// <remarks/>
        Validated,
        
        /// <remarks/>
        ZipCodeDoesNotExist,
        
        /// <remarks/>
        ZipCodeDoesNotMatchCityState,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public partial class TaxRateOutput
    {
        
        private string descriptionField;
        
        private double foodSalesTaxPercentField;
        
        private double freightSalesTaxPercentField;
        
        private double merchandiseSalesTaxPercentField;
        
        private double wineSalesTaxPercentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double FoodSalesTaxPercent
        {
            get
            {
                return this.foodSalesTaxPercentField;
            }
            set
            {
                this.foodSalesTaxPercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double FreightSalesTaxPercent
        {
            get
            {
                return this.freightSalesTaxPercentField;
            }
            set
            {
                this.freightSalesTaxPercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double MerchandiseSalesTaxPercent
        {
            get
            {
                return this.merchandiseSalesTaxPercentField;
            }
            set
            {
                this.merchandiseSalesTaxPercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double WineSalesTaxPercent
        {
            get
            {
                return this.wineSalesTaxPercentField;
            }
            set
            {
                this.wineSalesTaxPercentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public partial class GetSalesTaxRatesByAddressResponse
    {
        
        private Error[] errorsField;
        
        private TaxRateAddressOutput processedAddressField;
        
        private ResponseStatus responseStatusField;
        
        private TaxRateOutput taxRatesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Error[] Errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TaxRateAddressOutput ProcessedAddress
        {
            get
            {
                return this.processedAddressField;
            }
            set
            {
                this.processedAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ResponseStatus ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TaxRateOutput TaxRates
        {
            get
            {
                return this.taxRatesField;
            }
            set
            {
                this.taxRatesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public partial class AddressOption
    {
        
        private bool ignoreStreetLevelErrorsField;
        
        private bool rejectIfAddressSuggestedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IgnoreStreetLevelErrors
        {
            get
            {
                return this.ignoreStreetLevelErrorsField;
            }
            set
            {
                this.ignoreStreetLevelErrorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool RejectIfAddressSuggested
        {
            get
            {
                return this.rejectIfAddressSuggestedField;
            }
            set
            {
                this.rejectIfAddressSuggestedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public partial class Address
    {
        
        private string cityField;
        
        private string companyField;
        
        private string countryField;
        
        private string countyField;
        
        private System.DateTime dateOfBirthField;
        
        private string emailField;
        
        private string faxField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string phoneField;
        
        private string stateField;
        
        private string street1Field;
        
        private string street2Field;
        
        private string zip1Field;
        
        private string zip2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string County
        {
            get
            {
                return this.countyField;
            }
            set
            {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime DateOfBirth
        {
            get
            {
                return this.dateOfBirthField;
            }
            set
            {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Fax
        {
            get
            {
                return this.faxField;
            }
            set
            {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Street1
        {
            get
            {
                return this.street1Field;
            }
            set
            {
                this.street1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Street2
        {
            get
            {
                return this.street2Field;
            }
            set
            {
                this.street2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Zip1
        {
            get
            {
                return this.zip1Field;
            }
            set
            {
                this.zip1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Zip2
        {
            get
            {
                return this.zip2Field;
            }
            set
            {
                this.zip2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public partial class CalculateSalesTaxItem
    {
        
        private string brandKeyField;
        
        private string productKeyField;
        
        private double productQuantityField;
        
        private double productUnitPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BrandKey
        {
            get
            {
                return this.brandKeyField;
            }
            set
            {
                this.brandKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ProductKey
        {
            get
            {
                return this.productKeyField;
            }
            set
            {
                this.productKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double ProductQuantity
        {
            get
            {
                return this.productQuantityField;
            }
            set
            {
                this.productQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double ProductUnitPrice
        {
            get
            {
                return this.productUnitPriceField;
            }
            set
            {
                this.productUnitPriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public partial class Security
    {
        
        private string instanceIDField;
        
        private string partnerKeyField;
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InstanceID
        {
            get
            {
                return this.instanceIDField;
            }
            set
            {
                this.instanceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PartnerKey
        {
            get
            {
                return this.partnerKeyField;
            }
            set
            {
                this.partnerKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetTaxRateRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CalculateSalesTaxDueForOrderRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetSalesTaxRatesByAddressRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public abstract partial class BaseRequest
    {
        
        private Security securityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Security Security
        {
            get
            {
                return this.securityField;
            }
            set
            {
                this.securityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public partial class GetTaxRateRequest : BaseRequest
    {
        
        private Address addressField;
        
        private AddressOption addressOptionField;
        
        private bool withZipPlus4RatesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Address Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AddressOption AddressOption
        {
            get
            {
                return this.addressOptionField;
            }
            set
            {
                this.addressOptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool WithZipPlus4Rates
        {
            get
            {
                return this.withZipPlus4RatesField;
            }
            set
            {
                this.withZipPlus4RatesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public partial class CalculateSalesTaxDueForOrderRequest : BaseRequest
    {
        
        private TaxRateAddressInput shipToAddressField;
        
        private System.Nullable<System.DateTime> effectiveDateField;
        
        private TaxSaleType taxSaleTypeField;
        
        private System.Nullable<double> shippingAndHandlingCollectedField;
        
        private CalculateSalesTaxItem[] orderItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TaxRateAddressInput ShipToAddress
        {
            get
            {
                return this.shipToAddressField;
            }
            set
            {
                this.shipToAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> EffectiveDate
        {
            get
            {
                return this.effectiveDateField;
            }
            set
            {
                this.effectiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TaxSaleType TaxSaleType
        {
            get
            {
                return this.taxSaleTypeField;
            }
            set
            {
                this.taxSaleTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<double> ShippingAndHandlingCollected
        {
            get
            {
                return this.shippingAndHandlingCollectedField;
            }
            set
            {
                this.shippingAndHandlingCollectedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public CalculateSalesTaxItem[] OrderItems
        {
            get
            {
                return this.orderItemsField;
            }
            set
            {
                this.orderItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shipcompliant.com/")]
    public enum TaxSaleType
    {
        
        /// <remarks/>
        Null,
        
        /// <remarks/>
        Offsite,
        
        /// <remarks/>
        Onsite,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface TaxServiceSoapChannel : ShipcompliantTax.TaxServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class TaxServiceSoapClient : System.ServiceModel.ClientBase<ShipcompliantTax.TaxServiceSoap>, ShipcompliantTax.TaxServiceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TaxServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(TaxServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), TaxServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaxServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TaxServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaxServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TaxServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaxServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ShipcompliantTax.GetSalesTaxRatesByAddressResponse> GetSalesTaxRatesByAddressAsync(ShipcompliantTax.GetSalesTaxRatesByAddressRequest Request)
        {
            return base.Channel.GetSalesTaxRatesByAddressAsync(Request);
        }
        
        public System.Threading.Tasks.Task<ShipcompliantTax.CalculateSalesTaxDueForOrderResponse> CalculateSalesTaxDueForOrderAsync(ShipcompliantTax.CalculateSalesTaxDueForOrderRequest Request)
        {
            return base.Channel.CalculateSalesTaxDueForOrderAsync(Request);
        }
        
        public System.Threading.Tasks.Task<ShipcompliantTax.GetTaxRateResponse> GetTaxRateAsync(ShipcompliantTax.GetTaxRateRequest Request)
        {
            return base.Channel.GetTaxRateAsync(Request);
        }
        
        public System.Threading.Tasks.Task<string> GetVersionAsync()
        {
            return base.Channel.GetVersionAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TaxServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TaxServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TaxServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://ws-dev.shipcompliant.com/Services/1.3/TaxService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.TaxServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://ws-dev.shipcompliant.com/Services/1.3/TaxService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            TaxServiceSoap,
            
            TaxServiceSoap12,
        }
    }
}
