//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VintegrateWebService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRequest", Namespace="http://www.vintegrate.com/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VintegrateWebService.UpsertCustomerRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VintegrateWebService.GetCustomerRequest))]
    public partial class BaseRequest : object
    {
        
        private string PartnerKeyField;
        
        private string UserNameField;
        
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PartnerKey
        {
            get
            {
                return this.PartnerKeyField;
            }
            set
            {
                this.PartnerKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpsertCustomerRequest", Namespace="http://www.vintegrate.com/")]
    public partial class UpsertCustomerRequest : VintegrateWebService.BaseRequest
    {
        
        private string CustomerIDField;
        
        private string EmailAddressField;
        
        private string ContactLastNameField;
        
        private string ContactFirstNameField;
        
        private string ContactCompanyNameField;
        
        private string ContactPhone1Field;
        
        private string ContactPhone2Field;
        
        private string ContactPhone3Field;
        
        private string DateOfBirthField;
        
        private string CustomerSinceField;
        
        private string ContactAddress1Field;
        
        private string ContactAddress2Field;
        
        private string ContactAddress3Field;
        
        private string ContactCityField;
        
        private string ContactStateField;
        
        private string ContactZipField;
        
        private string SalesRepNameField;
        
        private string AccountTypeField;
        
        private bool PreferEmailCommunicationField;
        
        private bool PreferPhoneCommunicationField;
        
        private bool PreferNoCommunicationField;
        
        private string BilltoLastNameField;
        
        private string BilltoFirstNameField;
        
        private string BilltoCompanyNameField;
        
        private string BilltoPhone1Field;
        
        private string BilltoPhone2Field;
        
        private string BilltoPhone3Field;
        
        private string BilltoAddress1Field;
        
        private string BilltoAddress2Field;
        
        private string BilltoAddress3Field;
        
        private string BilltoCityField;
        
        private string BilltoStateField;
        
        private string BilltoZipField;
        
        private string ShipToLastNameField;
        
        private string ShipToFirstNameField;
        
        private string ShipToCompanyNameField;
        
        private string ShipToPhone1Field;
        
        private string ShipToPhone2Field;
        
        private string ShipToPhone3Field;
        
        private string ShipToAddress1Field;
        
        private string ShipToAddress2Field;
        
        private string ShipToAddress3Field;
        
        private string ShipToCityField;
        
        private string ShipToStateField;
        
        private string ShipToZipField;
        
        private string ReferralSourceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ContactLastName
        {
            get
            {
                return this.ContactLastNameField;
            }
            set
            {
                this.ContactLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ContactFirstName
        {
            get
            {
                return this.ContactFirstNameField;
            }
            set
            {
                this.ContactFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ContactCompanyName
        {
            get
            {
                return this.ContactCompanyNameField;
            }
            set
            {
                this.ContactCompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ContactPhone1
        {
            get
            {
                return this.ContactPhone1Field;
            }
            set
            {
                this.ContactPhone1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ContactPhone2
        {
            get
            {
                return this.ContactPhone2Field;
            }
            set
            {
                this.ContactPhone2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ContactPhone3
        {
            get
            {
                return this.ContactPhone3Field;
            }
            set
            {
                this.ContactPhone3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string DateOfBirth
        {
            get
            {
                return this.DateOfBirthField;
            }
            set
            {
                this.DateOfBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CustomerSince
        {
            get
            {
                return this.CustomerSinceField;
            }
            set
            {
                this.CustomerSinceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ContactAddress1
        {
            get
            {
                return this.ContactAddress1Field;
            }
            set
            {
                this.ContactAddress1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ContactAddress2
        {
            get
            {
                return this.ContactAddress2Field;
            }
            set
            {
                this.ContactAddress2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ContactAddress3
        {
            get
            {
                return this.ContactAddress3Field;
            }
            set
            {
                this.ContactAddress3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string ContactCity
        {
            get
            {
                return this.ContactCityField;
            }
            set
            {
                this.ContactCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string ContactState
        {
            get
            {
                return this.ContactStateField;
            }
            set
            {
                this.ContactStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string ContactZip
        {
            get
            {
                return this.ContactZipField;
            }
            set
            {
                this.ContactZipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string SalesRepName
        {
            get
            {
                return this.SalesRepNameField;
            }
            set
            {
                this.SalesRepNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string AccountType
        {
            get
            {
                return this.AccountTypeField;
            }
            set
            {
                this.AccountTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public bool PreferEmailCommunication
        {
            get
            {
                return this.PreferEmailCommunicationField;
            }
            set
            {
                this.PreferEmailCommunicationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public bool PreferPhoneCommunication
        {
            get
            {
                return this.PreferPhoneCommunicationField;
            }
            set
            {
                this.PreferPhoneCommunicationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public bool PreferNoCommunication
        {
            get
            {
                return this.PreferNoCommunicationField;
            }
            set
            {
                this.PreferNoCommunicationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string BilltoLastName
        {
            get
            {
                return this.BilltoLastNameField;
            }
            set
            {
                this.BilltoLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string BilltoFirstName
        {
            get
            {
                return this.BilltoFirstNameField;
            }
            set
            {
                this.BilltoFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string BilltoCompanyName
        {
            get
            {
                return this.BilltoCompanyNameField;
            }
            set
            {
                this.BilltoCompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string BilltoPhone1
        {
            get
            {
                return this.BilltoPhone1Field;
            }
            set
            {
                this.BilltoPhone1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string BilltoPhone2
        {
            get
            {
                return this.BilltoPhone2Field;
            }
            set
            {
                this.BilltoPhone2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string BilltoPhone3
        {
            get
            {
                return this.BilltoPhone3Field;
            }
            set
            {
                this.BilltoPhone3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string BilltoAddress1
        {
            get
            {
                return this.BilltoAddress1Field;
            }
            set
            {
                this.BilltoAddress1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string BilltoAddress2
        {
            get
            {
                return this.BilltoAddress2Field;
            }
            set
            {
                this.BilltoAddress2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string BilltoAddress3
        {
            get
            {
                return this.BilltoAddress3Field;
            }
            set
            {
                this.BilltoAddress3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string BilltoCity
        {
            get
            {
                return this.BilltoCityField;
            }
            set
            {
                this.BilltoCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string BilltoState
        {
            get
            {
                return this.BilltoStateField;
            }
            set
            {
                this.BilltoStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string BilltoZip
        {
            get
            {
                return this.BilltoZipField;
            }
            set
            {
                this.BilltoZipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string ShipToLastName
        {
            get
            {
                return this.ShipToLastNameField;
            }
            set
            {
                this.ShipToLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public string ShipToFirstName
        {
            get
            {
                return this.ShipToFirstNameField;
            }
            set
            {
                this.ShipToFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=35)]
        public string ShipToCompanyName
        {
            get
            {
                return this.ShipToCompanyNameField;
            }
            set
            {
                this.ShipToCompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=36)]
        public string ShipToPhone1
        {
            get
            {
                return this.ShipToPhone1Field;
            }
            set
            {
                this.ShipToPhone1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=37)]
        public string ShipToPhone2
        {
            get
            {
                return this.ShipToPhone2Field;
            }
            set
            {
                this.ShipToPhone2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=38)]
        public string ShipToPhone3
        {
            get
            {
                return this.ShipToPhone3Field;
            }
            set
            {
                this.ShipToPhone3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public string ShipToAddress1
        {
            get
            {
                return this.ShipToAddress1Field;
            }
            set
            {
                this.ShipToAddress1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=40)]
        public string ShipToAddress2
        {
            get
            {
                return this.ShipToAddress2Field;
            }
            set
            {
                this.ShipToAddress2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=41)]
        public string ShipToAddress3
        {
            get
            {
                return this.ShipToAddress3Field;
            }
            set
            {
                this.ShipToAddress3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=42)]
        public string ShipToCity
        {
            get
            {
                return this.ShipToCityField;
            }
            set
            {
                this.ShipToCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=43)]
        public string ShipToState
        {
            get
            {
                return this.ShipToStateField;
            }
            set
            {
                this.ShipToStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=44)]
        public string ShipToZip
        {
            get
            {
                return this.ShipToZipField;
            }
            set
            {
                this.ShipToZipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=45)]
        public string ReferralSource
        {
            get
            {
                return this.ReferralSourceField;
            }
            set
            {
                this.ReferralSourceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCustomerRequest", Namespace="http://www.vintegrate.com/")]
    public partial class GetCustomerRequest : VintegrateWebService.BaseRequest
    {
        
        private string EMailAddressField;
        
        private string CustomerIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EMailAddress
        {
            get
            {
                return this.EMailAddressField;
            }
            set
            {
                this.EMailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://www.vintegrate.com/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VintegrateWebService.UpsertCustomerResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VintegrateWebService.GetCustomerResponse))]
    public partial class BaseResponse : object
    {
        
        private bool StatusField;
        
        private string MessageField;
        
        private int RecordCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int RecordCount
        {
            get
            {
                return this.RecordCountField;
            }
            set
            {
                this.RecordCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpsertCustomerResponse", Namespace="http://www.vintegrate.com/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VintegrateWebService.GetCustomerRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VintegrateWebService.BaseRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VintegrateWebService.GetCustomerResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VintegrateWebService.BaseResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VintegrateWebService.Customer[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VintegrateWebService.Customer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VintegrateWebService.CustomerWineClub[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VintegrateWebService.CustomerWineClub))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VintegrateWebService.UpsertCustomerRequest))]
    public partial class UpsertCustomerResponse : VintegrateWebService.BaseResponse
    {
        
        private object CustomerIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCustomerResponse", Namespace="http://www.vintegrate.com/")]
    public partial class GetCustomerResponse : VintegrateWebService.BaseResponse
    {
        
        private VintegrateWebService.Customer[] CustomerInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public VintegrateWebService.Customer[] CustomerInfo
        {
            get
            {
                return this.CustomerInfoField;
            }
            set
            {
                this.CustomerInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://www.vintegrate.com/")]
    public partial class Customer : object
    {
        
        private string CustomerIDField;
        
        private string EmailAddressField;
        
        private string ContactLastNameField;
        
        private string ContactFirstNameField;
        
        private string ContactCompanyNameField;
        
        private string ContactPhone1Field;
        
        private string ContactPhone2Field;
        
        private string ContactPhone3Field;
        
        private System.DateTime DateOfBirthField;
        
        private System.DateTime CustomerSinceField;
        
        private string ContactAddress1Field;
        
        private string ContactAddress2Field;
        
        private string ContactAddress3Field;
        
        private string ContactCityField;
        
        private string ContactStateField;
        
        private string ContactZipField;
        
        private string AccountTypeField;
        
        private bool PreferEmailCommunicationField;
        
        private bool PreferPhoneCommunicationField;
        
        private bool PreferNoCommunicationField;
        
        private string BilltoLastNameField;
        
        private string BilltoFirstNameField;
        
        private string BilltoCompanyNameField;
        
        private string BilltoPhone1Field;
        
        private string BilltoPhone2Field;
        
        private string BilltoPhone3Field;
        
        private string BilltoAddress1Field;
        
        private string BilltoAddress2Field;
        
        private string BilltoAddress3Field;
        
        private string BilltoCityField;
        
        private string BilltoStateField;
        
        private string BilltoZipField;
        
        private string ShipToLastNameField;
        
        private string ShipToFirstNameField;
        
        private string ShipToCompanyNameField;
        
        private string ShipToPhone1Field;
        
        private string ShipToPhone2Field;
        
        private string ShipToPhone3Field;
        
        private string ShipToAddress1Field;
        
        private string ShipToAddress2Field;
        
        private string ShipToAddress3Field;
        
        private string ShipToCityField;
        
        private string ShipToStateField;
        
        private string ShipToZipField;
        
        private string SalesRepNameField;
        
        private VintegrateWebService.CustomerWineClub[] WineClubsField;
        
        private System.DateTime CustomerModifiedDateField;
        
        private System.DateTime BilltoModifiedDateField;
        
        private System.DateTime ContactModifiedDateField;
        
        private System.DateTime ShiptoModifiedDateField;
        
        private string ReferralSourceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ContactLastName
        {
            get
            {
                return this.ContactLastNameField;
            }
            set
            {
                this.ContactLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ContactFirstName
        {
            get
            {
                return this.ContactFirstNameField;
            }
            set
            {
                this.ContactFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ContactCompanyName
        {
            get
            {
                return this.ContactCompanyNameField;
            }
            set
            {
                this.ContactCompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ContactPhone1
        {
            get
            {
                return this.ContactPhone1Field;
            }
            set
            {
                this.ContactPhone1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ContactPhone2
        {
            get
            {
                return this.ContactPhone2Field;
            }
            set
            {
                this.ContactPhone2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ContactPhone3
        {
            get
            {
                return this.ContactPhone3Field;
            }
            set
            {
                this.ContactPhone3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime DateOfBirth
        {
            get
            {
                return this.DateOfBirthField;
            }
            set
            {
                this.DateOfBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime CustomerSince
        {
            get
            {
                return this.CustomerSinceField;
            }
            set
            {
                this.CustomerSinceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ContactAddress1
        {
            get
            {
                return this.ContactAddress1Field;
            }
            set
            {
                this.ContactAddress1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ContactAddress2
        {
            get
            {
                return this.ContactAddress2Field;
            }
            set
            {
                this.ContactAddress2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ContactAddress3
        {
            get
            {
                return this.ContactAddress3Field;
            }
            set
            {
                this.ContactAddress3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string ContactCity
        {
            get
            {
                return this.ContactCityField;
            }
            set
            {
                this.ContactCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string ContactState
        {
            get
            {
                return this.ContactStateField;
            }
            set
            {
                this.ContactStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string ContactZip
        {
            get
            {
                return this.ContactZipField;
            }
            set
            {
                this.ContactZipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string AccountType
        {
            get
            {
                return this.AccountTypeField;
            }
            set
            {
                this.AccountTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public bool PreferEmailCommunication
        {
            get
            {
                return this.PreferEmailCommunicationField;
            }
            set
            {
                this.PreferEmailCommunicationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public bool PreferPhoneCommunication
        {
            get
            {
                return this.PreferPhoneCommunicationField;
            }
            set
            {
                this.PreferPhoneCommunicationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public bool PreferNoCommunication
        {
            get
            {
                return this.PreferNoCommunicationField;
            }
            set
            {
                this.PreferNoCommunicationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string BilltoLastName
        {
            get
            {
                return this.BilltoLastNameField;
            }
            set
            {
                this.BilltoLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string BilltoFirstName
        {
            get
            {
                return this.BilltoFirstNameField;
            }
            set
            {
                this.BilltoFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string BilltoCompanyName
        {
            get
            {
                return this.BilltoCompanyNameField;
            }
            set
            {
                this.BilltoCompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string BilltoPhone1
        {
            get
            {
                return this.BilltoPhone1Field;
            }
            set
            {
                this.BilltoPhone1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string BilltoPhone2
        {
            get
            {
                return this.BilltoPhone2Field;
            }
            set
            {
                this.BilltoPhone2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string BilltoPhone3
        {
            get
            {
                return this.BilltoPhone3Field;
            }
            set
            {
                this.BilltoPhone3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string BilltoAddress1
        {
            get
            {
                return this.BilltoAddress1Field;
            }
            set
            {
                this.BilltoAddress1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string BilltoAddress2
        {
            get
            {
                return this.BilltoAddress2Field;
            }
            set
            {
                this.BilltoAddress2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string BilltoAddress3
        {
            get
            {
                return this.BilltoAddress3Field;
            }
            set
            {
                this.BilltoAddress3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string BilltoCity
        {
            get
            {
                return this.BilltoCityField;
            }
            set
            {
                this.BilltoCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string BilltoState
        {
            get
            {
                return this.BilltoStateField;
            }
            set
            {
                this.BilltoStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string BilltoZip
        {
            get
            {
                return this.BilltoZipField;
            }
            set
            {
                this.BilltoZipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string ShipToLastName
        {
            get
            {
                return this.ShipToLastNameField;
            }
            set
            {
                this.ShipToLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string ShipToFirstName
        {
            get
            {
                return this.ShipToFirstNameField;
            }
            set
            {
                this.ShipToFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public string ShipToCompanyName
        {
            get
            {
                return this.ShipToCompanyNameField;
            }
            set
            {
                this.ShipToCompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=35)]
        public string ShipToPhone1
        {
            get
            {
                return this.ShipToPhone1Field;
            }
            set
            {
                this.ShipToPhone1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=36)]
        public string ShipToPhone2
        {
            get
            {
                return this.ShipToPhone2Field;
            }
            set
            {
                this.ShipToPhone2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=37)]
        public string ShipToPhone3
        {
            get
            {
                return this.ShipToPhone3Field;
            }
            set
            {
                this.ShipToPhone3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=38)]
        public string ShipToAddress1
        {
            get
            {
                return this.ShipToAddress1Field;
            }
            set
            {
                this.ShipToAddress1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public string ShipToAddress2
        {
            get
            {
                return this.ShipToAddress2Field;
            }
            set
            {
                this.ShipToAddress2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=40)]
        public string ShipToAddress3
        {
            get
            {
                return this.ShipToAddress3Field;
            }
            set
            {
                this.ShipToAddress3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=41)]
        public string ShipToCity
        {
            get
            {
                return this.ShipToCityField;
            }
            set
            {
                this.ShipToCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=42)]
        public string ShipToState
        {
            get
            {
                return this.ShipToStateField;
            }
            set
            {
                this.ShipToStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=43)]
        public string ShipToZip
        {
            get
            {
                return this.ShipToZipField;
            }
            set
            {
                this.ShipToZipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=44)]
        public string SalesRepName
        {
            get
            {
                return this.SalesRepNameField;
            }
            set
            {
                this.SalesRepNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=45)]
        public VintegrateWebService.CustomerWineClub[] WineClubs
        {
            get
            {
                return this.WineClubsField;
            }
            set
            {
                this.WineClubsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=46)]
        public System.DateTime CustomerModifiedDate
        {
            get
            {
                return this.CustomerModifiedDateField;
            }
            set
            {
                this.CustomerModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=47)]
        public System.DateTime BilltoModifiedDate
        {
            get
            {
                return this.BilltoModifiedDateField;
            }
            set
            {
                this.BilltoModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=48)]
        public System.DateTime ContactModifiedDate
        {
            get
            {
                return this.ContactModifiedDateField;
            }
            set
            {
                this.ContactModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=49)]
        public System.DateTime ShiptoModifiedDate
        {
            get
            {
                return this.ShiptoModifiedDateField;
            }
            set
            {
                this.ShiptoModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=50)]
        public string ReferralSource
        {
            get
            {
                return this.ReferralSourceField;
            }
            set
            {
                this.ReferralSourceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerWineClub", Namespace="http://www.vintegrate.com/")]
    public partial class CustomerWineClub : object
    {
        
        private string WineClubField;
        
        private string WineClubSegmentField;
        
        private string WineClubShiptoLastNameField;
        
        private string WineClubShiptoFirstNameField;
        
        private string WineClubShiptoCompanyField;
        
        private string WineClubShiptoAddress1Field;
        
        private string WineClubShiptoAddress2Field;
        
        private string WineClubShiptoAddress3Field;
        
        private string WineClubShipToCityField;
        
        private string WineClubShiptoStateField;
        
        private string WineClubShiptoZipField;
        
        private string WineClubSalesRepField;
        
        private System.DateTime WineClubSignUpDateField;
        
        private System.DateTime WineClubVacationStartDateField;
        
        private System.DateTime WineClubVacationEndDateField;
        
        private System.DateTime WineClubCancellationDateField;
        
        private string WineClubCancellationReasonField;
        
        private string WineClubPreferredFulfillmentMethodField;
        
        private string WineClubPreferredCarrierField;
        
        private string WineClubPreferredShipmentMethodField;
        
        private bool WineClubGiftMembershipField;
        
        private string WineClubGiftGiverLastNameField;
        
        private string WineClubGiftGiverFirstNameField;
        
        private string WineClubGiftGiverCompanyField;
        
        private string WineClubGiftGiverAddress1Field;
        
        private string WineClubGiftGiverAddress2Field;
        
        private string WineClubGiftGiverAddress3Field;
        
        private string WineClubGiftGiverCityField;
        
        private string WineClubGiftGiverStateField;
        
        private string WineClubGiftGiverZipField;
        
        private string WineClubGiftGiverPhoneField;
        
        private string WineClubGiftGiverPhone2Field;
        
        private string WineClubGiftGiverPhone3Field;
        
        private System.DateTime WineClubModifiedDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string WineClub
        {
            get
            {
                return this.WineClubField;
            }
            set
            {
                this.WineClubField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string WineClubSegment
        {
            get
            {
                return this.WineClubSegmentField;
            }
            set
            {
                this.WineClubSegmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string WineClubShiptoLastName
        {
            get
            {
                return this.WineClubShiptoLastNameField;
            }
            set
            {
                this.WineClubShiptoLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string WineClubShiptoFirstName
        {
            get
            {
                return this.WineClubShiptoFirstNameField;
            }
            set
            {
                this.WineClubShiptoFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string WineClubShiptoCompany
        {
            get
            {
                return this.WineClubShiptoCompanyField;
            }
            set
            {
                this.WineClubShiptoCompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string WineClubShiptoAddress1
        {
            get
            {
                return this.WineClubShiptoAddress1Field;
            }
            set
            {
                this.WineClubShiptoAddress1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string WineClubShiptoAddress2
        {
            get
            {
                return this.WineClubShiptoAddress2Field;
            }
            set
            {
                this.WineClubShiptoAddress2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string WineClubShiptoAddress3
        {
            get
            {
                return this.WineClubShiptoAddress3Field;
            }
            set
            {
                this.WineClubShiptoAddress3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string WineClubShipToCity
        {
            get
            {
                return this.WineClubShipToCityField;
            }
            set
            {
                this.WineClubShipToCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string WineClubShiptoState
        {
            get
            {
                return this.WineClubShiptoStateField;
            }
            set
            {
                this.WineClubShiptoStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string WineClubShiptoZip
        {
            get
            {
                return this.WineClubShiptoZipField;
            }
            set
            {
                this.WineClubShiptoZipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string WineClubSalesRep
        {
            get
            {
                return this.WineClubSalesRepField;
            }
            set
            {
                this.WineClubSalesRepField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.DateTime WineClubSignUpDate
        {
            get
            {
                return this.WineClubSignUpDateField;
            }
            set
            {
                this.WineClubSignUpDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.DateTime WineClubVacationStartDate
        {
            get
            {
                return this.WineClubVacationStartDateField;
            }
            set
            {
                this.WineClubVacationStartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.DateTime WineClubVacationEndDate
        {
            get
            {
                return this.WineClubVacationEndDateField;
            }
            set
            {
                this.WineClubVacationEndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public System.DateTime WineClubCancellationDate
        {
            get
            {
                return this.WineClubCancellationDateField;
            }
            set
            {
                this.WineClubCancellationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string WineClubCancellationReason
        {
            get
            {
                return this.WineClubCancellationReasonField;
            }
            set
            {
                this.WineClubCancellationReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string WineClubPreferredFulfillmentMethod
        {
            get
            {
                return this.WineClubPreferredFulfillmentMethodField;
            }
            set
            {
                this.WineClubPreferredFulfillmentMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string WineClubPreferredCarrier
        {
            get
            {
                return this.WineClubPreferredCarrierField;
            }
            set
            {
                this.WineClubPreferredCarrierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string WineClubPreferredShipmentMethod
        {
            get
            {
                return this.WineClubPreferredShipmentMethodField;
            }
            set
            {
                this.WineClubPreferredShipmentMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public bool WineClubGiftMembership
        {
            get
            {
                return this.WineClubGiftMembershipField;
            }
            set
            {
                this.WineClubGiftMembershipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string WineClubGiftGiverLastName
        {
            get
            {
                return this.WineClubGiftGiverLastNameField;
            }
            set
            {
                this.WineClubGiftGiverLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string WineClubGiftGiverFirstName
        {
            get
            {
                return this.WineClubGiftGiverFirstNameField;
            }
            set
            {
                this.WineClubGiftGiverFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string WineClubGiftGiverCompany
        {
            get
            {
                return this.WineClubGiftGiverCompanyField;
            }
            set
            {
                this.WineClubGiftGiverCompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string WineClubGiftGiverAddress1
        {
            get
            {
                return this.WineClubGiftGiverAddress1Field;
            }
            set
            {
                this.WineClubGiftGiverAddress1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string WineClubGiftGiverAddress2
        {
            get
            {
                return this.WineClubGiftGiverAddress2Field;
            }
            set
            {
                this.WineClubGiftGiverAddress2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string WineClubGiftGiverAddress3
        {
            get
            {
                return this.WineClubGiftGiverAddress3Field;
            }
            set
            {
                this.WineClubGiftGiverAddress3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string WineClubGiftGiverCity
        {
            get
            {
                return this.WineClubGiftGiverCityField;
            }
            set
            {
                this.WineClubGiftGiverCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string WineClubGiftGiverState
        {
            get
            {
                return this.WineClubGiftGiverStateField;
            }
            set
            {
                this.WineClubGiftGiverStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string WineClubGiftGiverZip
        {
            get
            {
                return this.WineClubGiftGiverZipField;
            }
            set
            {
                this.WineClubGiftGiverZipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string WineClubGiftGiverPhone
        {
            get
            {
                return this.WineClubGiftGiverPhoneField;
            }
            set
            {
                this.WineClubGiftGiverPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string WineClubGiftGiverPhone2
        {
            get
            {
                return this.WineClubGiftGiverPhone2Field;
            }
            set
            {
                this.WineClubGiftGiverPhone2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string WineClubGiftGiverPhone3
        {
            get
            {
                return this.WineClubGiftGiverPhone3Field;
            }
            set
            {
                this.WineClubGiftGiverPhone3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=33)]
        public System.DateTime WineClubModifiedDate
        {
            get
            {
                return this.WineClubModifiedDateField;
            }
            set
            {
                this.WineClubModifiedDateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.vintegrate.com/", ConfigurationName="VintegrateWebService.CustomerServiceSoap")]
    public interface CustomerServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vintegrate.com/CellarPassGetCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<VintegrateWebService.CellarPassGetCustomerResponse> CellarPassGetCustomerAsync(VintegrateWebService.CellarPassGetCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.vintegrate.com/CellarPassUpsertCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<VintegrateWebService.CellarPassUpsertCustomerResponse> CellarPassUpsertCustomerAsync(VintegrateWebService.CellarPassUpsertCustomerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CellarPassGetCustomerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CellarPassGetCustomer", Namespace="http://www.vintegrate.com/", Order=0)]
        public VintegrateWebService.CellarPassGetCustomerRequestBody Body;
        
        public CellarPassGetCustomerRequest()
        {
        }
        
        public CellarPassGetCustomerRequest(VintegrateWebService.CellarPassGetCustomerRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.vintegrate.com/")]
    public partial class CellarPassGetCustomerRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VintegrateWebService.GetCustomerRequest CustomerRequest;
        
        public CellarPassGetCustomerRequestBody()
        {
        }
        
        public CellarPassGetCustomerRequestBody(VintegrateWebService.GetCustomerRequest CustomerRequest)
        {
            this.CustomerRequest = CustomerRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CellarPassGetCustomerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CellarPassGetCustomerResponse", Namespace="http://www.vintegrate.com/", Order=0)]
        public VintegrateWebService.CellarPassGetCustomerResponseBody Body;
        
        public CellarPassGetCustomerResponse()
        {
        }
        
        public CellarPassGetCustomerResponse(VintegrateWebService.CellarPassGetCustomerResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.vintegrate.com/")]
    public partial class CellarPassGetCustomerResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VintegrateWebService.GetCustomerResponse CellarPassGetCustomerResult;
        
        public CellarPassGetCustomerResponseBody()
        {
        }
        
        public CellarPassGetCustomerResponseBody(VintegrateWebService.GetCustomerResponse CellarPassGetCustomerResult)
        {
            this.CellarPassGetCustomerResult = CellarPassGetCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CellarPassUpsertCustomerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CellarPassUpsertCustomer", Namespace="http://www.vintegrate.com/", Order=0)]
        public VintegrateWebService.CellarPassUpsertCustomerRequestBody Body;
        
        public CellarPassUpsertCustomerRequest()
        {
        }
        
        public CellarPassUpsertCustomerRequest(VintegrateWebService.CellarPassUpsertCustomerRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.vintegrate.com/")]
    public partial class CellarPassUpsertCustomerRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VintegrateWebService.UpsertCustomerRequest CustomerRequest;
        
        public CellarPassUpsertCustomerRequestBody()
        {
        }
        
        public CellarPassUpsertCustomerRequestBody(VintegrateWebService.UpsertCustomerRequest CustomerRequest)
        {
            this.CustomerRequest = CustomerRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CellarPassUpsertCustomerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CellarPassUpsertCustomerResponse", Namespace="http://www.vintegrate.com/", Order=0)]
        public VintegrateWebService.CellarPassUpsertCustomerResponseBody Body;
        
        public CellarPassUpsertCustomerResponse()
        {
        }
        
        public CellarPassUpsertCustomerResponse(VintegrateWebService.CellarPassUpsertCustomerResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.vintegrate.com/")]
    public partial class CellarPassUpsertCustomerResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VintegrateWebService.UpsertCustomerResponse CellarPassUpsertCustomerResult;
        
        public CellarPassUpsertCustomerResponseBody()
        {
        }
        
        public CellarPassUpsertCustomerResponseBody(VintegrateWebService.UpsertCustomerResponse CellarPassUpsertCustomerResult)
        {
            this.CellarPassUpsertCustomerResult = CellarPassUpsertCustomerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface CustomerServiceSoapChannel : VintegrateWebService.CustomerServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class CustomerServiceSoapClient : System.ServiceModel.ClientBase<VintegrateWebService.CustomerServiceSoap>, VintegrateWebService.CustomerServiceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CustomerServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CustomerServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), CustomerServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CustomerServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CustomerServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VintegrateWebService.CellarPassGetCustomerResponse> VintegrateWebService.CustomerServiceSoap.CellarPassGetCustomerAsync(VintegrateWebService.CellarPassGetCustomerRequest request)
        {
            return base.Channel.CellarPassGetCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<VintegrateWebService.CellarPassGetCustomerResponse> CellarPassGetCustomerAsync(VintegrateWebService.GetCustomerRequest CustomerRequest)
        {
            VintegrateWebService.CellarPassGetCustomerRequest inValue = new VintegrateWebService.CellarPassGetCustomerRequest();
            inValue.Body = new VintegrateWebService.CellarPassGetCustomerRequestBody();
            inValue.Body.CustomerRequest = CustomerRequest;
            return ((VintegrateWebService.CustomerServiceSoap)(this)).CellarPassGetCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VintegrateWebService.CellarPassUpsertCustomerResponse> VintegrateWebService.CustomerServiceSoap.CellarPassUpsertCustomerAsync(VintegrateWebService.CellarPassUpsertCustomerRequest request)
        {
            return base.Channel.CellarPassUpsertCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<VintegrateWebService.CellarPassUpsertCustomerResponse> CellarPassUpsertCustomerAsync(VintegrateWebService.UpsertCustomerRequest CustomerRequest)
        {
            VintegrateWebService.CellarPassUpsertCustomerRequest inValue = new VintegrateWebService.CellarPassUpsertCustomerRequest();
            inValue.Body = new VintegrateWebService.CellarPassUpsertCustomerRequestBody();
            inValue.Body.CustomerRequest = CustomerRequest;
            return ((VintegrateWebService.CustomerServiceSoap)(this)).CellarPassUpsertCustomerAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomerServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CustomerServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomerServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://cellarpass.vintegrate.com/services/customer.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.CustomerServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://cellarpass.vintegrate.com/services/customer.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CustomerServiceSoap,
            
            CustomerServiceSoap12,
        }
    }
}
